import React from 'react';
import { X } from 'lucide-react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'terms' | 'privacy' | null;
}

export default function LegalModal({ isOpen, onClose, type }: LegalModalProps) {
  if (!isOpen || !type) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-gray-900/40 dark:bg-gray-900/80 backdrop-blur-sm">
      <div className="bg-white dark:bg-gray-900 rounded-3xl shadow-2xl w-full max-w-3xl max-h-[80vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200 border border-transparent dark:border-gray-800">
        <div className="flex items-center justify-between p-6 border-b border-gray-100 dark:border-gray-800">
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
            {type === 'terms' ? 'Terms & Conditions' : 'Privacy Policy'}
          </h2>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-full transition-colors"
          >
            <X size={24} />
          </button>
        </div>
        
        <div className="p-6 overflow-y-auto prose prose-indigo dark:prose-invert max-w-none text-gray-600 dark:text-gray-300">
          {type === 'terms' ? (
            <>
              <h3>1. Acceptance of Terms</h3>
              <p>
                By accessing and using Bernard Fiagbenu's Cloud (the "Website"), you accept and agree to be bound by the terms and provision of this agreement.
              </p>
              
              <h3>2. Intellectual Property</h3>
              <p>
                All content, features, and functionality on this Website, including but not limited to text, graphics, logos, and software, are the exclusive property of Bernard Fiagbenu and are protected by international copyright, trademark, and other intellectual property laws.
              </p>
              
              <h3>3. User Conduct</h3>
              <p>
                You agree to use the Website only for lawful purposes. You are prohibited from violating or attempting to violate the security of the Website, including accessing data not intended for you or logging onto a server or an account which you are not authorized to access.
              </p>

              <h3>4. AI Assistant Usage</h3>
              <p>
                The Website features an AI assistant powered by Google Gemini. Responses generated by the AI are for informational purposes only. We do not guarantee the accuracy, completeness, or usefulness of any information provided by the AI assistant.
              </p>
              
              <h3>5. Disclaimer of Warranties</h3>
              <p>
                The Website is provided on an "as is" and "as available" basis. Bernard Fiagbenu makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
              </p>
              
              <h3>6. Limitations</h3>
              <p>
                In no event shall Bernard Fiagbenu be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on the Website.
              </p>
            </>
          ) : (
            <>
              <h3>1. Information We Collect</h3>
              <p>
                When you visit the Website, we may collect certain information about your device, your interaction with the Website, and information necessary to process your requests.
              </p>
              <ul>
                <li><strong>Usage Data:</strong> We may collect information on how the Website is accessed and used.</li>
                <li><strong>Microphone Data:</strong> If you use the voice feature of our AI assistant, we request access to your microphone. Audio data is processed in real-time for transcription purposes and is not permanently stored by us.</li>
                <li><strong>Location Data:</strong> If you use the maps feature of our AI assistant, we may request your geolocation to provide accurate, location-based responses.</li>
              </ul>

              <h3>2. How We Use Your Information</h3>
              <p>
                We use the collected information for various purposes:
              </p>
              <ul>
                <li>To provide and maintain our Website</li>
                <li>To provide interactive features like the AI Chatbot</li>
                <li>To monitor the usage of our Website</li>
                <li>To detect, prevent and address technical issues</li>
              </ul>

              <h3>3. Third-Party Services</h3>
              <p>
                We use third-party services, specifically Google Gemini API, to power our AI assistant. When you interact with the chatbot, your text, audio, and location inputs may be processed by Google's servers in accordance with their privacy policies.
              </p>

              <h3>4. Data Security</h3>
              <p>
                The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
              </p>

              <h3>5. Changes to This Privacy Policy</h3>
              <p>
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
              </p>
            </>
          )}
        </div>
        
        <div className="p-6 border-t border-gray-100 dark:border-gray-800 bg-gray-50 dark:bg-gray-900 flex justify-end">
          <button
            onClick={onClose}
            className="px-6 py-2.5 bg-gray-900 dark:bg-indigo-600 text-white font-medium rounded-full hover:bg-gray-800 dark:hover:bg-indigo-700 transition-colors"
          >
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
}
